version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "proj4-producer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kz5ygckvqh2x"
s3_prefix = "proj4-producer"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=570465827932.dkr.ecr.us-east-2.amazonaws.com/proj4_producer"]
